#!/usr/bin/env bash
set -e

export COLUMNS=80
export LINES=29

PAD_SOCKET=/home/pad/.socket
PAD_OUTPUT="nc -q0 -U $PAD_SOCKET"

error() { echo $1; exit 1; }

if [ -z "$1" ]; then
  ${PAD_OUTPUT}
elif [ "$1" = "start" ]; then
  clear
  nc -lkU "$PAD_SOCKET"
elif [ "$1" = "clear" ]; then
  clear | ${PAD_OUTPUT}
elif [ "$1" = "config" ]; then
  [[ $EUID -ne 0 ]] && error "sudo required"
  echo "Set SSH password for the pad user"
  passwd -q pad
elif [ "$1" = "note" ]; then
  echo "Your pad is ready to edit..."
  nano ${HOME}/.notes | ${PAD_OUTPUT}
elif [ "$1" = "shell" ]; then
  cat - | ${PAD_OUTPUT}
else
  echo "Please! Watch on pad... "
  exec "$@" | ${PAD_OUTPUT}
fi
