#!/usr/bin/env bash
set -e

PAD_LIB=/var/lib/pad
PAD_SOCKET=/usr/lib/pad/pad.sock

PAD_OUTPUT="nc -q0 -U $PAD_SOCKET"

USER_HOME="$(getent passwd $(logname) | cut -d: -f6)"
SSH_LOGIN="ssh -i ${USER_HOME}/.ssh/pad -oStrictHostKeyChecking=no -t $(logname)@$(hostname)"

source ${USER_HOME}/.padrc

error() { echo $1; exit 1; }

if [ -z "$1" ]; then
  ${PAD_OUTPUT}
elif [ "$1" = "start" ]; then
  pad banner
  nc -lkU "${PAD_SOCKET}"
elif [ "$1" = "banner" ]; then
  clear
  figlet "< pad >"
  echo ""
  echo "Created by Francesco Bianco <bianco@javanile.org>"
  echo "Thanks to Lara & Tancredi"
  echo ""
  echo "* * *"
elif [ "$1" = "clear" ]; then
  clear | ${PAD_OUTPUT}
elif [ "$1" = "config" ]; then
  [[ $EUID -ne 0 ]] && error "sudo required"
  echo "Set SSH password for the pad user"
  passwd -q pad
elif [ "$1" = "note" ]; then
  echo "Your pad is ready to edit..."
  nano ${USER_HOME}/.notes | ${PAD_OUTPUT}
elif [ "$1" = "shell" ]; then
  $SSH_LOGIN bash --rcfile ${PAD_LIB}/.padrc -i | ${PAD_OUTPUT}
else
  echo "Please! Watch on pad... "
  exec "$@" | ${PAD_OUTPUT}
fi
